### PR TITLE
Extend the blog with about pymc info

### PR DESCRIPTION
**Pull request by OriolAbril**
You can check the preview in the checks section below. I think this will make the blog "publishable". The changes are:
* I have added an intro about the PyMC project and its activities beyond developing the PyMC library
* I have updated the announcements
* I have moved some of the content from the About section of the docs (if we have it here we can remove it from the versioned docs and convert in to an external link pointing to this website)
* I have copied the notebook from https://github.com/pymc-devs/pymc-examples/pull/303 here. I have only added a post directive to it, everything else, text, code and outputs is untouched.
* I extended the external links section
* (infrastructure only) I have removed the github pages workflow as it was not needed, readthedocs already builds both main website and PR previews and is easier to maintain

There is no need to keep all the changes, we can go back to a blog scope only for example. cc @twiecki @mjhajharia @reshamas

Things that need to be decided:
* Scope of the website: blog only or project info + blog?
* ~url of the website. The idea is to [host this at `pymc.io`](https://discourse.pymc.io/t/proposal-create-a-page-pymc-io-which-acts-as-a-news-feed-for-pymc/8661) and this hasn't changed, but readthedocs by default adds the `/en/latest/` suffix to the url.~ 
  
  ~This can be configured and removed to host a versionless page, but it's either both present or none present. versions make no sense here, so the `latest` is useless, but if we choose the versionless mode, the `en` will also go and we won't be able to translate the website~
  - Note: translating sphinx generated websites is not complicated, I tried it out at https://sphinx-primer.readthedocs.io/ca/latest/ (you can see it now has a catalan version) using [transifex](https://www.transifex.com/arviz/sphinx-primer-website/dashboard/).

Things that need to be done:
* @twiecki has to make the url decision above a reality once we choose something (I already made you a maintainer of https://readthedocs.org/projects/pymcio/)

### CODE REVIEW

**Comment by twiecki** [comment]
> url of the website. The idea is to [host this at pymc.io](https://discourse.pymc.io/t/proposal-create-a-page-pymc-io-which-acts-as-a-news-feed-for-pymc/8661) and this hasn't changed, but readthedocs by default adds the /en/latest/ suffix to the url.

Can we have both? Where the main website `https://pymc.io` has the (versionless) front-page, blog etc. And that links to the docs (https://docs.pymc.io/en/latest/)?

If not, I think having the front-page be versioned (and identical between the versions) would be my second choice.

**Comment by OriolAbril** [comment]
> Can we have both? Where the main website https://pymc.io has the (versionless) front-page, blog etc. And that links to the docs (https://docs.pymc.io/en/latest/)?

We can have versionless front-page, the issue is that versionless means no translations ever. But I have seen that the pydata theme has just added a version switcher option independent of readthedocs so if we ever wanted translations we can use that. I have just configured readthedocs to drop the `/en/latest/` for this website (never for the actual docs). Can you make it serve on pymc.io?

**Comment by OriolAbril** [comment]
> Can you be more specific what I need to do?

I don't know exactly, whatever you did to get the readthedocs page for the versioned docs to be at `docs.pymc.io` but now for this readthedocs page (https://readthedocs.org/projects/pymcio/) to be at `pymc.io`

**Comment by twiecki** [comment]
OK, I enabled it.

**Comment by twiecki** [comment]
image

**Comment by OriolAbril** [comment]
Nice! Merging then, we can continue working on the content and especially on the v4 announcement in future PRs

**Comment by twiecki** [comment]
Oh nice, and seems to work!

**Comment by twiecki** [comment]
image

we should add a link to the GH repo here too.

**Comment by reshamas** [comment]
@OriolAbril @twiecki 

Is this the current URL of the PyMC blog?
https://www.pymc.io/index.html

PyMC blog repo:
https://github.com/pymc-devs/pymc.io

Wonder if this possible URL might be considered:
blog.pymc.io

**Comment by reshamas** [comment]
I see this is the PyMC blog URL, which is ok.  So, the blog code is in its own separate repo, it looks like:
https://www.pymc.io/blog.html

**Comment by OriolAbril** [comment]
Yes, the blog URL is https://www.pymc.io/blog.html. It is currently not possible to have it at `blog.pymc.io` because the whole website is generated together from the content of this repo. The only differences between blog and non-blog pages are the sidebar (configured [here](https://github.com/pymc-devs/pymc.io/blob/main/conf.py#L131)). 

We could separate the blog from the "homepage" but that would probably mean more work to maintain both websites. I am not sure it is worth it unless we got a non-sphinx based homepage in which case separating the two would be necessary. Do you think it will be confusing like this? (if it wasn't clear from my comments above, I don't understand how domains, subdomains or anything of the sort works)

**Comment by reshamas** [comment]
@OriolAbril 
I think it's ok. I was confused because for the blog repo, I would expect it to be called "pymc-blog" to know where the code is.

**Comment by reshamas** [comment]
@OriolAbril 
I am also a bit confused because this repo doesn't say "PyMC Blog" anywhere in the description, nor does it point directly to the blog repo.  See attached screenshot.


Screen Shot 2022-04-05 at 9 19 49 AM

**Comment by OriolAbril** [comment]
I'll create an issue to add a readme on the github repo in addition to #5. The blog is a section of the website and github doesn't allow multiple links in the about section

**Pull request merged**
